/** Stable machine codes for frontend-thrown errors (client guards + auth UI). */
export const FRONTEND_ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MFA_UNSUPPORTED: 'AUTH_MFA_UNSUPPORTED',
  AUTH_OAUTH_NO_REDIRECT: 'AUTH_OAUTH_NO_REDIRECT',
  AUTH_PASSKEY_CANCELLED: 'AUTH_PASSKEY_CANCELLED',
  INVITE_INVALID_OR_EXPIRED: 'INVITE_INVALID_OR_EXPIRED',
  MEMBER_ROLE_REQUIRED: 'MEMBER_ROLE_REQUIRED',
} as const;

export type FrontendErrorCode =
  (typeof FRONTEND_ERROR_CODES)[keyof typeof FRONTEND_ERROR_CODES];
