import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Plugin } from 'vite';

import {
  localeBuildProfileFor,
  resolveBuildI18nBcp47,
  resolveBuildI18nMode,
  uiLocaleFromBcp47,
} from '../src/lib/i18n/build-config.ts';
import { I18N_NAMESPACES, type I18nNamespace } from '../src/lib/i18n/namespaces.ts';

const VIRTUAL_ID = '\0virtual:core-fe-i18n-resources';
const RESOURCES_ENTRY = '@/lib/i18n/i18n-resources.ts';
const MULTI_RESOURCES = resolve(process.cwd(), 'src/lib/i18n/i18n-resources.multi.ts');

const ALL_NAMESPACES = Object.values(I18N_NAMESPACES);

function loadNamespaceJson(uiLocale: string, ns: I18nNamespace): Record<string, unknown> {
  const primary = resolve(process.cwd(), `src/locales/${uiLocale}/${ns}.json`);
  if (existsSync(primary)) {
    return JSON.parse(readFileSync(primary, 'utf8')) as Record<string, unknown>;
  }

  const fallback = resolve(process.cwd(), `src/locales/en/${ns}.json`);
  if (existsSync(fallback)) {
    return JSON.parse(readFileSync(fallback, 'utf8')) as Record<string, unknown>;
  }

  return {};
}

function renderSingleLocaleModule(bcp47: string): string {
  const uiLocale = uiLocaleFromBcp47(bcp47);
  const profile = localeBuildProfileFor(bcp47);
  const namespaces = Object.fromEntries(
    ALL_NAMESPACES.map((ns) => [ns, loadNamespaceJson(uiLocale, ns)]),
  );

  return `/* generated by i18n-build plugin — do not edit */
export const I18N_BUILD_MODE = 'single';
export const I18N_BUILD_BCP47 = ${JSON.stringify(bcp47)};
export const I18N_BUILD_UI_LOCALE = ${JSON.stringify(uiLocale)};

const I18N_BUNDLED_RESOURCES = {
  ${JSON.stringify(uiLocale)}: ${JSON.stringify(namespaces, null, 2)},
};

export function getBootstrapResources() {
  return I18N_BUNDLED_RESOURCES;
}

export function getBuildLocaleProfile() {
  return ${JSON.stringify(profile, null, 2)};
}
`;
}

export type I18nBuildPluginOptions = {
  modeFlag?: string;
  localeFlag?: string;
};

/**
 * BUILD_I18N_MODE switch:
 * - single (default): inline one locale (text + regional profile) into JS — no JSON assets
 * - multi: alias to runtime loader (`i18n-resources.multi.ts`) with lazy JSON chunks
 */
export function i18nBuild(options: I18nBuildPluginOptions = {}): Plugin {
  const mode = resolveBuildI18nMode(options.modeFlag);
  const bcp47 = resolveBuildI18nBcp47(options.localeFlag);
  const uiLocale = uiLocaleFromBcp47(bcp47);

  return {
    name: 'core-fe-i18n-build',
    config() {
      return {
        define: {
          'import.meta.env.VITE_I18N_BUILD_MODE': JSON.stringify(mode),
          'import.meta.env.VITE_I18N_BUILD_BCP47': JSON.stringify(bcp47),
          'import.meta.env.VITE_I18N_BUILD_UI_LOCALE': JSON.stringify(uiLocale),
        },
        resolve: {
          alias:
            mode === 'single'
              ? [{ find: RESOURCES_ENTRY, replacement: VIRTUAL_ID }]
              : [{ find: RESOURCES_ENTRY, replacement: MULTI_RESOURCES }],
        },
      };
    },
    resolveId(source) {
      if (mode === 'single' && source === VIRTUAL_ID) return VIRTUAL_ID;
      return undefined;
    },
    load(id) {
      if (mode === 'single' && id === VIRTUAL_ID) {
        return renderSingleLocaleModule(bcp47);
      }
      return undefined;
    },
  };
}
