/**
 * Env-var registry: catalog generator + schema-default emitter.
 *
 * Single source of truth is `src/core/config/env-schema.ts` (Zod schema +
 * `envFieldDescriptions` + per-env `envProfiles.defaults`) and the deploy
 * classification in `tooling/setup/setup.config.json` (`deploySecrets` /
 * `deployVariables`). This module only READS and derives — it never duplicates a
 * value — so the catalog and the sync can never disagree with the runtime.
 *
 * Modes:
 *   --catalog [--check]  (re)generate docs/reference/env-catalog.md. `--check`
 *                        fails (exit 1) on drift instead of writing.
 *   --defaults <env>     print JSON of `envProfiles.<env>.defaults` to stdout —
 *                        the bridge the Node `github:sync` reads to detect (and
 *                        prune) variables whose value equals the schema default.
 *
 * Run via tsx: `node --import tsx tooling/env-registry/env-registry.ts …`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  type AppEnvironment,
  envFieldDescriptions,
  envProfiles,
  envSchemaBase,
} from '../../src/core/config/env-schema.ts';

const PROJECT_ROOT = resolve(import.meta.dirname, '../..');
const CATALOG_PATH = resolve(PROJECT_ROOT, 'docs/reference/env-catalog.md');
const SETUP_CONFIG_PATH = resolve(PROJECT_ROOT, 'tooling/setup/setup.config.json');

type Kind = 'secret' | 'variable' | 'build·local';

interface SetupEnvironment {
  readonly name: string;
  readonly deploySecrets?: readonly string[];
  readonly deployVariables?: readonly string[];
}

/** Union classification across every configured environment (a key's kind is stable across envs). */
function loadClassification(): { secrets: Set<string>; variables: Set<string> } {
  const config = JSON.parse(readFileSync(SETUP_CONFIG_PATH, 'utf8')) as {
    environments?: readonly SetupEnvironment[];
  };
  const secrets = new Set<string>();
  const variables = new Set<string>();
  for (const environment of config.environments ?? []) {
    for (const key of environment.deploySecrets ?? []) secrets.add(key);
    for (const key of environment.deployVariables ?? []) variables.add(key);
  }
  return { secrets, variables };
}

/** Stringified Zod default (from `safeParse(undefined)`), or null when there is none. */
function schemaDefaults(): Map<string, string> {
  const defaults = new Map<string, string>();
  for (const [key, field] of Object.entries(envSchemaBase.shape)) {
    const parsed = field.safeParse(undefined);
    if (parsed.success && parsed.data !== undefined)
      defaults.set(key, String(parsed.data));
  }
  return defaults;
}

/** Per-env defaults as a Map (avoids dynamic index access on the typed Record). */
function profileDefaults(environment: AppEnvironment): Map<string, string> {
  const entry = new Map<string, string>();
  const profile = new Map(Object.entries(envProfiles)).get(environment);
  for (const [key, value] of Object.entries(profile?.defaults ?? {}))
    entry.set(key, value);
  return entry;
}

function classify(
  key: string,
  sets: { secrets: Set<string>; variables: Set<string> },
): Kind {
  if (sets.secrets.has(key)) return 'secret';
  if (sets.variables.has(key)) return 'variable';
  return 'build·local';
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

/** Build the catalog markdown deterministically (alphabetical) — stable for `--check`. */
function renderCatalog(): string {
  const sets = loadClassification();
  const zodDefaults = schemaDefaults();
  const devDefaults = profileDefaults('development');
  const prodDefaults = profileDefaults('production');
  const keys = Object.keys(envSchemaBase.shape).sort((a, b) => a.localeCompare(b));

  const codeOrDash = (value: string): string =>
    value ? `\`${escapeCell(value)}\`` : '—';
  const rows = keys.map((key) => {
    const kind = classify(key, sets);
    const schemaDefault = codeOrDash(zodDefaults.get(key) ?? '');
    const dev = codeOrDash(devDefaults.get(key) ?? '');
    const prod = codeOrDash(prodDefaults.get(key) ?? '');
    // eslint-disable-next-line security/detect-object-injection -- key from the schema, not user input
    const description = escapeCell(envFieldDescriptions[key] ?? '');
    return `| \`${key}\` | ${kind} | ${schemaDefault} | ${dev} | ${prod} | ${description} |`;
  });

  const secretList = [...sets.secrets].sort().map((key) => `- \`${key}\``);
  const variableList = [...sets.variables].sort().map((key) => `- \`${key}\``);

  return [
    '<!-- GENERATED by `pnpm env:catalog` — do not edit by hand. -->',
    '',
    '# Environment variable catalog',
    '',
    'Derived from [`src/core/config/env-schema.ts`](../../src/core/config/env-schema.ts)',
    '(Zod schema, `envFieldDescriptions`, per-env `envProfiles.defaults`) and the deploy',
    'classification in [`tooling/setup/setup.config.json`](../../tooling/setup/setup.config.json).',
    'Regenerate with `pnpm env:catalog`; `pnpm env:catalog:check` fails on drift.',
    '',
    '**Kind** — `secret`: GitHub Environment Secret (`secrets.*`), always pushed by',
    '`github:sync`. `variable`: GitHub Environment Variable (`vars.*`), pushed only when',
    'missing/different and pruned when equal to the schema default. `build·local`:',
    'build-time or local-only, never synced to a GitHub Environment.',
    '',
    '| Key | Kind | Schema default | development | production | Description |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
    '## Deploy secrets (`secrets.*`)',
    '',
    ...(secretList.length > 0 ? secretList : ['- _(none)_']),
    '',
    '## Deploy variables (`vars.*`)',
    '',
    'Diffed on `github:sync`: pushed only when missing or changed; a value equal to its',
    'runtime schema default (the env-independent Zod fallback) is not pushed and is pruned',
    'from GitHub (the runtime falls back to the identical default). The per-env columns',
    'above are scaffold values, which may differ. Preview with `pnpm github:sync <env> --diff`.',
    '',
    ...(variableList.length > 0 ? variableList : ['- _(none)_']),
    '',
  ].join('\n');
}

function runCatalog(check: boolean): void {
  const content = renderCatalog();
  if (check) {
    let current = '';
    try {
      current = readFileSync(CATALOG_PATH, 'utf8');
    } catch {
      // Missing file → treat as empty so the drift check reports it needs writing.
    }
    if (current !== content) {
      console.error(
        '✖ docs/reference/env-catalog.md is out of date. Regenerate: pnpm env:catalog',
      );
      process.exit(1);
    }
    console.log('env-catalog: up to date.');
    return;
  }
  writeFileSync(CATALOG_PATH, content);
  console.log(`Wrote ${CATALOG_PATH}`);
}

/**
 * Emit the RUNTIME-fallback defaults — the Zod schema defaults applied when a
 * variable is unset (env-INDEPENDENT). This is exactly what `github:sync` compares
 * against to prune a variable safely: prune ⇒ unset at deploy ⇒ the runtime falls
 * back to this same value. The per-env `envProfiles.defaults` are SCAFFOLD values,
 * not the runtime fallback — a dev flag whose profile default differs from the Zod
 * default (e.g. VITE_DEBUG_LOGGING dev `true` vs schema `false`) must be PUSHED, not
 * pruned, so the runtime-fallback map is the only correct basis for the prune.
 */
function runDefaults(): void {
  process.stdout.write(JSON.stringify(Object.fromEntries(schemaDefaults())));
}

function main(): void {
  const argv = process.argv.slice(2);
  if (argv.includes('--catalog')) {
    runCatalog(argv.includes('--check'));
    return;
  }
  if (argv.includes('--defaults')) {
    runDefaults();
    return;
  }
  console.error('Usage: env-registry.ts (--catalog [--check] | --defaults)');
  process.exit(1);
}

main();
