import { I18N_NAMESPACES } from '@/lib/i18n/namespaces.ts';

export const SETTINGS_NS = I18N_NAMESPACES.settings;

export const SETTINGS_KEYS = {
  nav: {
    ariaSections: 'nav.ariaSections',
    ariaSettings: 'nav.ariaSettings',
    searchPlaceholder: 'nav.searchPlaceholder',
    searchAria: 'nav.searchAria',
    empty: 'nav.empty',
    groups: {
      account: 'nav.groups.account',
      organization: 'nav.groups.organization',
    },
    profile: 'nav.profile',
    account: 'nav.account',
    security: 'nav.security',
    notifications: 'nav.notifications',
    sessions: 'nav.sessions',
    general: 'nav.general',
    members: 'nav.members',
    roles: 'nav.roles',
    branches: 'nav.branches',
    billing: 'nav.billing',
    integrations: 'nav.integrations',
  },
  security: {
    heading: 'security.heading',
    description: 'security.description',
    mfa: {
      title: 'security.mfa.title',
      description: 'security.mfa.description',
      enabled: 'security.mfa.enabled',
      disabled: 'security.mfa.disabled',
      setup: 'security.mfa.setup',
      disable: 'security.mfa.disable',
      disableTitle: 'security.mfa.disableTitle',
      disableDescription: 'security.mfa.disableDescription',
      disableConfirm: 'security.mfa.disableConfirm',
      setupTitle: 'security.mfa.setupTitle',
      setupDescription: 'security.mfa.setupDescription',
      recoveryTitle: 'security.mfa.recoveryTitle',
      recoveryDescription: 'security.mfa.recoveryDescription',
      done: 'security.mfa.done',
      cancel: 'security.mfa.cancel',
      verifyEnable: 'security.mfa.verifyEnable',
      codeLabel: 'security.mfa.codeLabel',
      codeAria: 'security.mfa.codeAria',
      secretLabel: 'security.mfa.secretLabel',
      copySecret: 'security.mfa.copySecret',
      copiedSecret: 'security.mfa.copiedSecret',
      scanHint: 'security.mfa.scanHint',
      errors: {
        setupFailed: 'security.mfa.errors.setupFailed',
        invalidCode: 'security.mfa.errors.invalidCode',
      },
    },
    passkeys: {
      title: 'security.passkeys.title',
      description: 'security.passkeys.description',
      add: 'security.passkeys.add',
      empty: 'security.passkeys.empty',
      removeAria: 'security.passkeys.removeAria',
      addTitle: 'security.passkeys.addTitle',
      addDescription: 'security.passkeys.addDescription',
      nameLabel: 'security.passkeys.nameLabel',
      namePlaceholder: 'security.passkeys.namePlaceholder',
      cancel: 'security.passkeys.cancel',
      submit: 'security.passkeys.submit',
    },
    overview: {
      title: 'security.overview.title',
      description: 'security.overview.description',
      score: 'security.overview.score',
      mfaOn: 'security.overview.mfaOn',
      mfaOff: 'security.overview.mfaOff',
      passkeysOn: 'security.overview.passkeysOn',
      passkeysOff: 'security.overview.passkeysOff',
      idleProtection: 'security.overview.idleProtection',
    },
    recoveryCodes: {
      reveal: 'security.recoveryCodes.reveal',
      hide: 'security.recoveryCodes.hide',
      copyAll: 'security.recoveryCodes.copyAll',
      download: 'security.recoveryCodes.download',
      copySuccess: 'security.recoveryCodes.copySuccess',
      copyFailed: 'security.recoveryCodes.copyFailed',
      downloadStarted: 'security.recoveryCodes.downloadStarted',
      clipboardNotice: 'security.recoveryCodes.clipboardNotice',
      acknowledge: 'security.recoveryCodes.acknowledge',
    },
  },
  discard: {
    title: 'discard.title',
    description: 'discard.description',
    stay: 'discard.stay',
    leave: 'discard.leave',
  },
  panels: {
    members: {
      title: 'panels.members.title',
      description: 'panels.members.description',
      loadFailed: 'panels.members.loadFailed',
      emptyTitle: 'panels.members.emptyTitle',
      emptyDescription: 'panels.members.emptyDescription',
      searchPlaceholder: 'panels.members.searchPlaceholder',
      noResults: 'panels.members.noResults',
      loadMore: 'panels.members.loadMore',
      removeAria: 'panels.members.removeAria',
      removeTitle: 'panels.members.removeTitle',
      removeDescription: 'panels.members.removeDescription',
      removeConfirm: 'panels.members.removeConfirm',
      removePending: 'panels.members.removePending',
    },
    roles: {
      title: 'panels.roles.title',
      description: 'panels.roles.description',
      loadFailed: 'panels.roles.loadFailed',
      emptyTitle: 'panels.roles.emptyTitle',
      emptyDescription: 'panels.roles.emptyDescription',
      searchPlaceholder: 'panels.roles.searchPlaceholder',
      noResults: 'panels.roles.noResults',
      loadMore: 'panels.roles.loadMore',
      systemBadge: 'panels.roles.systemBadge',
      memberCount: 'panels.roles.memberCount',
      memberCount_other: 'panels.roles.memberCount_other',
      deleteAria: 'panels.roles.deleteAria',
      deleteTitle: 'panels.roles.deleteTitle',
      deleteDescription: 'panels.roles.deleteDescription',
      deleteConfirm: 'panels.roles.deleteConfirm',
      deletePending: 'panels.roles.deletePending',
    },
    listSort: {
      label: 'panels.listSort.label',
      nameAsc: 'panels.listSort.nameAsc',
      nameDesc: 'panels.listSort.nameDesc',
      newest: 'panels.listSort.newest',
      oldest: 'panels.listSort.oldest',
    },
    profile: {
      title: 'panels.profile.title',
      description: 'panels.profile.description',
      completeness: 'panels.profile.completeness',
      confirmTitle: 'panels.profile.confirmTitle',
      confirmDescription: 'panels.profile.confirmDescription',
      confirmSave: 'panels.profile.confirmSave',
      confirmCancel: 'panels.profile.confirmCancel',
      saving: 'panels.profile.saving',
      save: 'panels.profile.save',
    },
    account: {
      deleteTitle: 'panels.account.deleteTitle',
      deleteDescription: 'panels.account.deleteDescription',
      deleteConfirm: 'panels.account.deleteConfirm',
      deleteCancel: 'panels.account.deleteCancel',
    },
  },
} as const;

export const SETTINGS_GROUP_LABEL_KEYS = {
  account: SETTINGS_KEYS.nav.groups.account,
  organization: SETTINGS_KEYS.nav.groups.organization,
} as const;

/** Build a settings section breadcrumb from scope + section labels. */
export function formatSettingsBreadcrumb(
  scopeLabel: string,
  sectionLabel: string,
): string {
  return `${scopeLabel} · ${sectionLabel}`;
}

export const SETTINGS_SECTION_LABEL_KEYS = {
  profile: SETTINGS_KEYS.nav.profile,
  account: SETTINGS_KEYS.nav.account,
  security: SETTINGS_KEYS.nav.security,
  notifications: SETTINGS_KEYS.nav.notifications,
  sessions: SETTINGS_KEYS.nav.sessions,
  general: SETTINGS_KEYS.nav.general,
  members: SETTINGS_KEYS.nav.members,
  roles: SETTINGS_KEYS.nav.roles,
  branches: SETTINGS_KEYS.nav.branches,
  billing: SETTINGS_KEYS.nav.billing,
  integrations: SETTINGS_KEYS.nav.integrations,
} as const;
