import {
  ArrowClockwiseIcon as ArrowClockwise,
  ArrowDownIcon as ArrowDown,
  ArrowUpIcon as ArrowUp,
  BellIcon as Bell,
  BellSlashIcon as BellSlash,
  BuildingsIcon as Buildings,
  CalendarBlankIcon as CalendarBlank,
  CaretDoubleLeftIcon as CaretDoubleLeft,
  CaretDoubleRightIcon as CaretDoubleRight,
  CaretLeftIcon as CaretLeft,
  CaretRightIcon as CaretRight,
  CaretUpDownIcon as CaretUpDown,
  CheckCircleIcon as CheckCircle,
  CheckIcon as Check,
  CircleNotchIcon as CircleNotch,
  CopyIcon as Copy,
  CreditCardIcon as CreditCard,
  DeviceMobileIcon as DeviceMobile,
  DevicesIcon as Devices,
  DotsThreeIcon as DotsThree,
  DownloadSimpleIcon as DownloadSimple,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  EyeSlashIcon as EyeSlash,
  FingerprintIcon as Fingerprint,
  GearIcon as Gear,
  GitBranchIcon as GitBranch,
  GithubLogoIcon as GithubLogo,
  GlobeIcon as Globe,
  LaptopIcon as Laptop,
  LightningIcon as Lightning,
  ListIcon as List,
  MagnifyingGlassIcon as MagnifyingGlass,
  MinusIcon as Minus,
  MonitorIcon as Monitor,
  MoonIcon as Moon,
  PaletteIcon as Palette,
  PlugIcon as Plug,
  PlusIcon as Plus,
  RocketIcon as Rocket,
  ShieldCheckIcon as ShieldCheck,
  ShieldIcon as Shield,
  ShieldWarningIcon as ShieldWarning,
  SignOutIcon as SignOut,
  SlidersHorizontalIcon as SlidersHorizontal,
  SparkleIcon as Sparkle,
  SquaresFourIcon as SquaresFour,
  StackIcon as Stack,
  SunIcon as Sun,
  TranslateIcon as Translate,
  TrashIcon as Trash,
  UserGearIcon as UserGear,
  UserIcon as User,
  UserPlusIcon as UserPlus,
  UsersIcon as Users,
  WarningCircleIcon as WarningCircle,
  WarningIcon as Warning,
  XCircleIcon as XCircle,
  XIcon as X,
} from '@phosphor-icons/react';

import type { IconName } from './icon-names.ts';
import type { AppIcon } from './icon-types.ts';

/** Phosphor equivalents of the canonical icon set (dynamically imported on demand). */
export const iconSet: Record<IconName, AppIcon> = {
  AlertCircle: WarningCircle,
  AlertTriangle: Warning,
  ArrowDown,
  ArrowUp,
  Bell,
  BellOff: BellSlash,
  Boxes: Stack,
  Building2: Buildings,
  CalendarDays: CalendarBlank,
  Check,
  CheckCircle2: CheckCircle,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronsLeft: CaretDoubleLeft,
  ChevronsRight: CaretDoubleRight,
  ChevronsUpDown: CaretUpDown,
  Copy,
  CreditCard,
  Download: DownloadSimple,
  Eye,
  EyeOff: EyeSlash,
  Fingerprint,
  GitBranch,
  Github: GithubLogo,
  Globe,
  Laptop,
  Languages: Translate,
  LayoutDashboard: SquaresFour,
  Loader2: CircleNotch,
  LogOut: SignOut,
  Mail: Envelope,
  Menu: List,
  Minus,
  Monitor,
  MonitorSmartphone: Devices,
  Moon,
  MoreHorizontal: DotsThree,
  Palette,
  Plus,
  Plug,
  Rocket,
  RotateCw: ArrowClockwise,
  Search: MagnifyingGlass,
  Settings: Gear,
  ShieldAlert: ShieldWarning,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone: DeviceMobile,
  Sparkles: Sparkle,
  Sun,
  Trash2: Trash,
  TriangleAlert: Warning,
  User,
  UserCog: UserGear,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap: Lightning,
};
