/**
 * Canonical icon names. The Lucide default set (in `index.ts`) and every
 * alternative set (`iconset-*.ts`) are keyed by these, so the type system
 * guarantees each library covers exactly the same icons. Kept in a leaf module
 * (no library imports) so the lazy alt-set chunks don't pull in the barrel.
 */
export const ICON_NAMES = [
  'AlertCircle',
  'AlertTriangle',
  'ArrowDown',
  'ArrowUp',
  'Bell',
  'BellOff',
  'Boxes',
  'Building2',
  'Check',
  'CheckCircle2',
  'ChevronLeft',
  'ChevronRight',
  'ChevronsLeft',
  'ChevronsRight',
  'ChevronsUpDown',
  'Copy',
  'Download',
  'Eye',
  'EyeOff',
  'Fingerprint',
  'Github',
  'Laptop',
  'LayoutDashboard',
  'Loader2',
  'LogOut',
  'Mail',
  'Menu',
  'Monitor',
  'Moon',
  'MoreHorizontal',
  'Palette',
  'Plus',
  'Rocket',
  'RotateCw',
  'Search',
  'Settings',
  'ShieldAlert',
  'ShieldCheck',
  'SlidersHorizontal',
  'Smartphone',
  'Sparkles',
  'Sun',
  'Trash2',
  'TriangleAlert',
  'UserPlus',
  'Users',
  'X',
  'XCircle',
  'Zap',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
