import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowUp,
  IconBell,
  IconBellOff,
  IconBolt,
  IconBoxMultiple,
  IconBrandGithub,
  IconBuilding,
  IconCalendarWeek,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircleCheck,
  IconCircleX,
  IconCopy,
  IconCreditCard,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDevices2,
  IconDots,
  IconDownload,
  IconEye,
  IconEyeOff,
  IconFingerprint,
  IconGitBranch,
  IconLanguage,
  IconLayoutDashboard,
  IconLoader2,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMinus,
  IconMoon,
  IconPalette,
  IconPlugConnected,
  IconPlus,
  IconRocket,
  IconRotateClockwise,
  IconSearch,
  IconSelector,
  IconSettings,
  IconShield,
  IconShieldCheck,
  IconShieldExclamation,
  IconSparkles,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCog,
  IconUserPlus,
  IconUsers,
  IconWorld,
  IconX,
} from '@tabler/icons-react';

import type { IconName } from './icon-names.ts';
import type { AppIcon } from './icon-types.ts';

/** Tabler equivalents of the canonical icon set (dynamically imported on demand). */
export const iconSet: Record<IconName, AppIcon> = {
  AlertCircle: IconAlertCircle,
  AlertTriangle: IconAlertTriangle,
  ArrowDown: IconArrowDown,
  ArrowUp: IconArrowUp,
  Bell: IconBell,
  BellOff: IconBellOff,
  Boxes: IconBoxMultiple,
  Building2: IconBuilding,
  CalendarDays: IconCalendarWeek,
  Check: IconCheck,
  CheckCircle2: IconCircleCheck,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ChevronsLeft: IconChevronsLeft,
  ChevronsRight: IconChevronsRight,
  ChevronsUpDown: IconSelector,
  Copy: IconCopy,
  CreditCard: IconCreditCard,
  Download: IconDownload,
  Eye: IconEye,
  EyeOff: IconEyeOff,
  Fingerprint: IconFingerprint,
  GitBranch: IconGitBranch,
  Github: IconBrandGithub,
  Globe: IconWorld,
  Laptop: IconDeviceLaptop,
  Languages: IconLanguage,
  LayoutDashboard: IconLayoutDashboard,
  Loader2: IconLoader2,
  LogOut: IconLogout,
  Mail: IconMail,
  Menu: IconMenu2,
  Minus: IconMinus,
  Monitor: IconDeviceDesktop,
  MonitorSmartphone: IconDevices2,
  Moon: IconMoon,
  MoreHorizontal: IconDots,
  Palette: IconPalette,
  Plus: IconPlus,
  Plug: IconPlugConnected,
  Rocket: IconRocket,
  RotateCw: IconRotateClockwise,
  Search: IconSearch,
  Settings: IconSettings,
  ShieldAlert: IconShieldExclamation,
  Shield: IconShield,
  ShieldCheck: IconShieldCheck,
  SlidersHorizontal: IconAdjustmentsHorizontal,
  Smartphone: IconDeviceMobile,
  Sparkles: IconSparkles,
  Sun: IconSun,
  Trash2: IconTrash,
  TriangleAlert: IconAlertTriangle,
  User: IconUser,
  UserCog: IconUserCog,
  UserPlus: IconUserPlus,
  Users: IconUsers,
  X: IconX,
  XCircle: IconCircleX,
  Zap: IconBolt,
};
