import {
  ArrowClockwise,
  ArrowDown,
  ArrowUp,
  Bell,
  BellSlash,
  Buildings,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretLeft,
  CaretRight,
  CaretUpDown,
  Check,
  CheckCircle,
  CircleNotch,
  Copy,
  DeviceMobile,
  DotsThree,
  DownloadSimple,
  Envelope,
  Eye,
  EyeSlash,
  Fingerprint,
  Gear,
  GithubLogo,
  Laptop,
  Lightning,
  List,
  MagnifyingGlass,
  Monitor,
  Moon,
  Palette,
  Plus,
  Rocket,
  ShieldCheck,
  ShieldWarning,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Stack,
  Sun,
  Trash,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  X,
  XCircle,
} from '@phosphor-icons/react';

import type { IconName } from './icon-names.ts';
import type { AppIcon } from './icon-types.ts';

/** Phosphor equivalents of the canonical icon set (dynamically imported on demand). */
export const iconSet: Record<IconName, AppIcon> = {
  AlertCircle: WarningCircle,
  AlertTriangle: Warning,
  ArrowDown,
  ArrowUp,
  Bell,
  BellOff: BellSlash,
  Boxes: Stack,
  Building2: Buildings,
  Check,
  CheckCircle2: CheckCircle,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronsLeft: CaretDoubleLeft,
  ChevronsRight: CaretDoubleRight,
  ChevronsUpDown: CaretUpDown,
  Copy,
  Download: DownloadSimple,
  Eye,
  EyeOff: EyeSlash,
  Fingerprint,
  Github: GithubLogo,
  Laptop,
  LayoutDashboard: SquaresFour,
  Loader2: CircleNotch,
  LogOut: SignOut,
  Mail: Envelope,
  Menu: List,
  Monitor,
  Moon,
  MoreHorizontal: DotsThree,
  Palette,
  Plus,
  Rocket,
  RotateCw: ArrowClockwise,
  Search: MagnifyingGlass,
  Settings: Gear,
  ShieldAlert: ShieldWarning,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone: DeviceMobile,
  Sparkles: Sparkle,
  Sun,
  Trash2: Trash,
  TriangleAlert: Warning,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap: Lightning,
};
