/**
 * Single icon surface for app code. Every icon import goes through here
 * (enforced by eslint no-restricted-imports), so swapping the icon library
 * is a one-file change. Vendored shadcn primitives (components/ui) import
 * lucide directly — they are replaced wholesale on `shadcn add`.
 */
export type { LucideIcon } from 'lucide-react';
export {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Bell,
  BellOff,
  Boxes,
  Building2,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Copy,
  Download,
  Eye,
  EyeOff,
  Fingerprint,
  Github,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  Plus,
  Rocket,
  RotateCw,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sun,
  Trash2,
  TriangleAlert,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap,
} from 'lucide-react';
